export const config = {
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER: process.env.TWILIO_NUMBER,
  RECIPIENT_PHONE_NUMBER: process.env.RECIPIENT_NUMBER,
  PORT: process.env.PORT || 5000,
};